/**
 * @fileoverview gRPC-Web generated client stub for geekCamp
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.0-rc2
// source: protocol/authorize.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as protocol_authorize_pb from '../protocol/authorize_pb';


export class AuthorizeClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetToken = new grpcWeb.MethodDescriptor(
    '/geekCamp.Authorize/GetToken',
    grpcWeb.MethodType.UNARY,
    protocol_authorize_pb.GetTokenRequest,
    protocol_authorize_pb.GetTokenReply,
    (request: protocol_authorize_pb.GetTokenRequest) => {
      return request.serializeBinary();
    },
    protocol_authorize_pb.GetTokenReply.deserializeBinary
  );

  getToken(
    request: protocol_authorize_pb.GetTokenRequest,
    metadata: grpcWeb.Metadata | null): Promise<protocol_authorize_pb.GetTokenReply>;

  getToken(
    request: protocol_authorize_pb.GetTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protocol_authorize_pb.GetTokenReply) => void): grpcWeb.ClientReadableStream<protocol_authorize_pb.GetTokenReply>;

  getToken(
    request: protocol_authorize_pb.GetTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protocol_authorize_pb.GetTokenReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/geekCamp.Authorize/GetToken',
        request,
        metadata || {},
        this.methodDescriptorGetToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/geekCamp.Authorize/GetToken',
    request,
    metadata || {},
    this.methodDescriptorGetToken);
  }

  methodDescriptorLinkToken = new grpcWeb.MethodDescriptor(
    '/geekCamp.Authorize/LinkToken',
    grpcWeb.MethodType.UNARY,
    protocol_authorize_pb.LinkTokenRequest,
    protocol_authorize_pb.LinkTokenReply,
    (request: protocol_authorize_pb.LinkTokenRequest) => {
      return request.serializeBinary();
    },
    protocol_authorize_pb.LinkTokenReply.deserializeBinary
  );

  linkToken(
    request: protocol_authorize_pb.LinkTokenRequest,
    metadata: grpcWeb.Metadata | null): Promise<protocol_authorize_pb.LinkTokenReply>;

  linkToken(
    request: protocol_authorize_pb.LinkTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protocol_authorize_pb.LinkTokenReply) => void): grpcWeb.ClientReadableStream<protocol_authorize_pb.LinkTokenReply>;

  linkToken(
    request: protocol_authorize_pb.LinkTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protocol_authorize_pb.LinkTokenReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/geekCamp.Authorize/LinkToken',
        request,
        metadata || {},
        this.methodDescriptorLinkToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/geekCamp.Authorize/LinkToken',
    request,
    metadata || {},
    this.methodDescriptorLinkToken);
  }

}

